### ISSUE TITLE
Make minutes before configurable

### ISSUE THREAD

**Issue by jkrauska** [c29r3/coda-snark-stopper#1]
https://github.com/c29r3/coda-snark-stopper/blob/master/snark-stopper.py#L81

It may be preferable to stop assigning new work 5 or 10 minutes before a block.
Make it a config.yml setting.

**Comment by c29r3** [comment]
> https://github.com/c29r3/coda-snark-stopper/blob/master/snark-stopper.py#L81
> 
> It may be preferable to stop assigning new work 5 or 10 minutes before a block.
> Make it a config.yml setting.

Thx, i will fix it
