### ISSUE TITLE
"message":"Field 'proposePubkeys' is not defined on type 'DaemonStatus'"

### ISSUE THREAD

**Issue by aquariusluo** [c29r3/coda-snark-stopper#2]
There is an error when i execute python3 snark-stopper.py
---------------
{"errors":[{"message":"Field 'proposePubkeys' is not defined on type 'DaemonStatus'"}]}
Traceback (most recent call last):
  File "snark-stopper.py", line 62, in <module>
    daemon_status = coda.get_daemon_status()
  File "/home/ubuntu/coda-snark-stopper/src/codaclient/CodaClient.py", line 160, in get_daemon_status
    res = self._send_query(query)
  File "/home/ubuntu/coda-snark-stopper/src/codaclient/CodaClient.py", line 37, in _send_query
    return self._graphql_request(query, variables)
  File "/home/ubuntu/coda-snark-stopper/src/codaclient/CodaClient.py", line 86, in _graphql_request
    "Query failed -- returned code {}. {} -> {}".format(response.status_code, query, response.json()))
Exception: Query failed -- returned code 200. query { daemonStatus { numAccounts blockchainLength highestBlockLengthReceived uptimeSecs ledgerMerkleRoot stateHash commitId peers userCommandsSent snarkWorker snarkWorkFee syncStatus proposePubkeys nextProposal consensusTimeBestTip consensusTimeNow consensusMechanism confDir commitId consensusConfiguration { delta k c cTimesK slotsPerEpoch slotDuration epochDuration acceptableNetworkDelay } } } -> {'errors': [{'message': "Field 'proposePubkeys' is not defined on type 'DaemonStatus'"}]}
ubuntu@ip-172-31-77-248:~/coda-snark-stopper$ sudo  python3 snark-stopper.py
{"errors":[{"message":"Field 'proposePubkeys' is not defined on type 'DaemonStatus'"}]}
Traceback (most recent call last):
  File "snark-stopper.py", line 62, in <module>
    daemon_status = coda.get_daemon_status()
  File "/home/ubuntu/coda-snark-stopper/src/codaclient/CodaClient.py", line 160, in get_daemon_status
    res = self._send_query(query)
  File "/home/ubuntu/coda-snark-stopper/src/codaclient/CodaClient.py", line 37, in _send_query
    return self._graphql_request(query, variables)
  File "/home/ubuntu/coda-snark-stopper/src/codaclient/CodaClient.py", line 86, in _graphql_request
    "Query failed -- returned code {}. {} -> {}".format(response.status_code, query, response.json()))
Exception: Query failed -- returned code 200. query { daemonStatus { numAccounts blockchainLength highestBlockLengthReceived uptimeSecs ledgerMerkleRoot stateHash commitId peers userCommandsSent snarkWorker snarkWorkFee syncStatus proposePubkeys nextProposal consensusTimeBestTip consensusTimeNow consensusMechanism confDir commitId consensusConfiguration { delta k c cTimesK slotsPerEpoch slotDuration epochDuration acceptableNetworkDelay } } } -> {'errors': [{'message': "Field 'proposePubkeys' is not defined on type 'DaemonStatus'"}]}

**Comment by c29r3** [comment]
@aquariusluo The developers once again made changes to the Coda API, because of this the old code stopped working. I made the necessary changes, now everything should work. You need to update
```
cd coda-snark-stopper \
&& git pull \
&& pip3 install -r requirements.txt
```

**Comment by aquariusluo** [comment]
Nice job, It works. Looking forward to good points.

Many thanks!

Sergey <notifications@github.com> 于2020年6月13日周六 上午3:51写道：
